### ISSUE TITLE
The libxc subsections of &XC_FUNCTIONAL are not recognized

### ISSUE THREAD

**Issue by ducryf** [cp2k/cp2k-input-tools#42]
Hi

I'm trying to parse an input file using the new libxc subsections of &XC_FUNCTIONAL. But these sections are not recognized and I get the following error:

cp2k_input_tools.parser_errors.InvalidSectionError: ("invalid section 'MGGA_C_R2SCAN'", defaultdict(<function Context.<locals>.<lambda> at 0x2b26fa545790>, {'filename': 'phonon.inp', 'linenr': 358, 'colnrs': [8], 'line': '&R2MGGA_C_SCAN', 'section': Section(name='XC_FUNCTIONAL', node=<Element 'SECTION' at 0x2b26f7505bd0>, subsections=[], keywords=[], param=None, repeats=False)}))

Can I somehow add these sections?

Thanks in advance,
Fabian

**Comment by dev-zero** [comment]
Can you please try with version 0.6.3?

We are using a bundled `cp2k_input.xml` as generated by CP2K with `cp2k.psmp --xml`.
When using the API you can specify an alternative file as the first argument to `CP2KInputPraser`: `cp2k_parser = CP2KInputParser("path/to/an/updated.xml")`. For the command line tools there is no option yet to specify an alternative file.

**Comment by ducryf** [comment]
Works like a charm. Thanks for the update and the explanation!
