### ISSUE TITLE
Release 0.9.0 on PyPI?

### ISSUE THREAD

**Issue by yakutovicha** [cp2k/cp2k-input-tools#99]
More and more packages require a bump of the Pydantic dependency. I was happy to see it has already happened for this library's [0.9.0](https://github.com/cp2k/cp2k-input-tools/releases/tag/v0.9.0) version.

However, for some reason, it didn't make it to PyPI. @dev-zero, do you know if it was intentional?

**Comment by dev-zero** [comment]
done, sorry for the delay
